// Mock data for demo mode

export const mockDashboardStats = {
  totalLeads: 127,
  activeLeads: 89,
  conversionRate: 24.5,
  totalRevenue: 45800000,
  averageDealSize: 4200000,
  revenueGrowth: 18.5,
  pipelineValue: 156000000,
  leadsByStatus: {
    SOURCING: 23,
    REGULATORY_ANALYSIS: 18,
    TECHNICAL_STUDY: 15,
    NETWORK_STUDY: 12,
    FONCIER: 9,
    ECONOMIC_MODEL: 6,
    QA_REVIEW: 4,
    VALIDATED: 28,
    REJECTED: 12,
  },
  recentActivity: [
    {
      id: '1',
      type: 'lead_created',
      leadName: 'Projet Salon-de-Provence 25MWc',
      userName: 'Guillaume Bougeard',
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '2',
      type: 'status_changed',
      leadName: 'Projet Aix-en-Provence 18MWc',
      userName: 'Mathéo Degras',
      from: 'TECHNICAL_STUDY',
      to: 'NETWORK_STUDY',
      timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: '3',
      type: 'lead_validated',
      leadName: 'Projet Montpellier 12MWc',
      userName: 'Hortense Foillard',
      timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  topPerformers: [
    { userId: '1', name: 'Guillaume Bougeard', leadsCreated: 24, revenue: 12500000 },
    { userId: '2', name: 'Mathéo Degras', leadsCreated: 21, revenue: 10800000 },
    { userId: '3', name: 'Lucas Lamquet', leadsCreated: 18, revenue: 9200000 },
  ],
  revenueGoals: [
    { month: 'Jan', revenueGoal: 30000000, revenueAchieved: 28500000 },
    { month: 'Fév', revenueGoal: 30000000, revenueAchieved: 31200000 },
    { month: 'Mar', revenueGoal: 35000000, revenueAchieved: 33800000 },
    { month: 'Avr', revenueGoal: 35000000, revenueAchieved: 36500000 },
    { month: 'Mai', revenueGoal: 40000000, revenueAchieved: 42100000 },
    { month: 'Juin', revenueGoal: 40000000, revenueAchieved: 39800000 },
  ],
};

export const mockLeads = [
  // SOURCING
  {
    id: '1',
    name: 'Projet Salon-de-Provence 25MWc',
    location: 'Salon-de-Provence (13)',
    coordinates: '43.6234,5.0981',
    surfaceArea: 25.5,
    capacityMWc: 25,
    status: 'SOURCING',
    assignedToId: '1',
    assignedTo: { firstName: 'Guillaume', lastName: 'Bougeard' },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 5200000,
    qualityScore: 85,
  },
  {
    id: '2',
    name: 'Projet Arles 15MWc',
    location: 'Arles (13)',
    coordinates: '43.6771,4.6309',
    surfaceArea: 15.3,
    capacityMWc: 15,
    status: 'SOURCING',
    assignedToId: '2',
    assignedTo: { firstName: 'Mathéo', lastName: 'Degras' },
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 3100000,
    qualityScore: 72,
  },
  {
    id: '3',
    name: 'Projet Carpentras 8MWc',
    location: 'Carpentras (84)',
    coordinates: '44.0556,5.0481',
    surfaceArea: 8.5,
    capacityMWc: 8,
    status: 'SOURCING',
    assignedToId: '3',
    assignedTo: { firstName: 'Lucas', lastName: 'Lamquet' },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 1700000,
    qualityScore: 68,
  },
  // REGULATORY_ANALYSIS
  {
    id: '4',
    name: 'Projet Avignon 20MWc',
    location: 'Avignon (84)',
    coordinates: '43.9493,4.8055',
    surfaceArea: 20.2,
    capacityMWc: 20,
    status: 'REGULATORY_ANALYSIS',
    assignedToId: '1',
    assignedTo: { firstName: 'Guillaume', lastName: 'Bougeard' },
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 4200000,
    qualityScore: 81,
  },
  {
    id: '5',
    name: 'Projet Nîmes 18MWc',
    location: 'Nîmes (30)',
    coordinates: '43.8367,4.3601',
    surfaceArea: 18.8,
    capacityMWc: 18,
    status: 'REGULATORY_ANALYSIS',
    assignedToId: '2',
    assignedTo: { firstName: 'Mathéo', lastName: 'Degras' },
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 3800000,
    qualityScore: 76,
  },
  // TECHNICAL_STUDY
  {
    id: '6',
    name: 'Projet Aix-en-Provence 22MWc',
    location: 'Aix-en-Provence (13)',
    coordinates: '43.5297,5.4474',
    surfaceArea: 22.1,
    capacityMWc: 22,
    status: 'TECHNICAL_STUDY',
    assignedToId: '3',
    assignedTo: { firstName: 'Lucas', lastName: 'Lamquet' },
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 4600000,
    qualityScore: 88,
  },
  {
    id: '7',
    name: 'Projet Béziers 14MWc',
    location: 'Béziers (34)',
    coordinates: '43.3439,3.2150',
    surfaceArea: 14.5,
    capacityMWc: 14,
    status: 'TECHNICAL_STUDY',
    assignedToId: '1',
    assignedTo: { firstName: 'Guillaume', lastName: 'Bougeard' },
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 2900000,
    qualityScore: 79,
  },
  // NETWORK_STUDY
  {
    id: '8',
    name: 'Projet Montpellier 16MWc',
    location: 'Montpellier (34)',
    coordinates: '43.6108,3.8767',
    surfaceArea: 16.3,
    capacityMWc: 16,
    status: 'NETWORK_STUDY',
    assignedToId: '2',
    assignedTo: { firstName: 'Mathéo', lastName: 'Degras' },
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 3400000,
    qualityScore: 84,
  },
  {
    id: '9',
    name: 'Projet Perpignan 10MWc',
    location: 'Perpignan (66)',
    coordinates: '42.6886,2.8948',
    surfaceArea: 10.2,
    capacityMWc: 10,
    status: 'NETWORK_STUDY',
    assignedToId: '3',
    assignedTo: { firstName: 'Lucas', lastName: 'Lamquet' },
    createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 2100000,
    qualityScore: 73,
  },
  // FONCIER
  {
    id: '10',
    name: 'Projet Toulouse 30MWc',
    location: 'Toulouse (31)',
    coordinates: '43.6047,1.4442',
    surfaceArea: 30.5,
    capacityMWc: 30,
    status: 'FONCIER',
    assignedToId: '1',
    assignedTo: { firstName: 'Guillaume', lastName: 'Bougeard' },
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 6300000,
    qualityScore: 91,
  },
  {
    id: '11',
    name: 'Projet Bordeaux 24MWc',
    location: 'Bordeaux (33)',
    coordinates: '44.8378,-0.5792',
    surfaceArea: 24.8,
    capacityMWc: 24,
    status: 'FONCIER',
    assignedToId: '2',
    assignedTo: { firstName: 'Mathéo', lastName: 'Degras' },
    createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 5000000,
    qualityScore: 86,
  },
  // ECONOMIC_MODEL
  {
    id: '12',
    name: 'Projet La Rochelle 19MWc',
    location: 'La Rochelle (17)',
    coordinates: '46.1591,-1.1520',
    surfaceArea: 19.2,
    capacityMWc: 19,
    status: 'ECONOMIC_MODEL',
    assignedToId: '3',
    assignedTo: { firstName: 'Lucas', lastName: 'Lamquet' },
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 4000000,
    qualityScore: 89,
  },
  {
    id: '13',
    name: 'Projet Poitiers 13MWc',
    location: 'Poitiers (86)',
    coordinates: '46.5802,0.3404',
    surfaceArea: 13.5,
    capacityMWc: 13,
    status: 'ECONOMIC_MODEL',
    assignedToId: '1',
    assignedTo: { firstName: 'Guillaume', lastName: 'Bougeard' },
    createdAt: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 2700000,
    qualityScore: 82,
  },
  // QA_REVIEW
  {
    id: '14',
    name: 'Projet Lyon 28MWc',
    location: 'Lyon (69)',
    coordinates: '45.7640,4.8357',
    surfaceArea: 28.3,
    capacityMWc: 28,
    status: 'QA_REVIEW',
    assignedToId: '2',
    assignedTo: { firstName: 'Mathéo', lastName: 'Degras' },
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 5900000,
    qualityScore: 93,
  },
  {
    id: '15',
    name: 'Projet Grenoble 17MWc',
    location: 'Grenoble (38)',
    coordinates: '45.1885,5.7245',
    surfaceArea: 17.1,
    capacityMWc: 17,
    status: 'QA_REVIEW',
    assignedToId: '3',
    assignedTo: { firstName: 'Lucas', lastName: 'Lamquet' },
    createdAt: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 3600000,
    qualityScore: 87,
  },
  // VALIDATED
  {
    id: '16',
    name: 'Projet Valence 21MWc',
    location: 'Valence (26)',
    coordinates: '44.9334,4.8924',
    surfaceArea: 21.4,
    capacityMWc: 21,
    status: 'VALIDATED',
    assignedToId: '1',
    assignedTo: { firstName: 'Guillaume', lastName: 'Bougeard' },
    createdAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 4400000,
    qualityScore: 95,
  },
  {
    id: '17',
    name: 'Projet Clermont-Ferrand 11MWc',
    location: 'Clermont-Ferrand (63)',
    coordinates: '45.7772,3.0870',
    surfaceArea: 11.2,
    capacityMWc: 11,
    status: 'VALIDATED',
    assignedToId: '2',
    assignedTo: { firstName: 'Mathéo', lastName: 'Degras' },
    createdAt: new Date(Date.now() - 48 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 2300000,
    qualityScore: 90,
  },
  // REJECTED
  {
    id: '18',
    name: 'Projet Tours 9MWc',
    location: 'Tours (37)',
    coordinates: '47.3941,0.6848',
    surfaceArea: 9.1,
    capacityMWc: 9,
    status: 'REJECTED',
    assignedToId: '3',
    assignedTo: { firstName: 'Lucas', lastName: 'Lamquet' },
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    estimatedRevenue: 1900000,
    qualityScore: 45,
  },
];

export const mockUsers = [
  { id: '1', firstName: 'Hortense', lastName: 'Foillard', email: 'hortense@lfs.fr', role: 'ADMIN' },
  { id: '2', firstName: 'Guillaume', lastName: 'Bougeard', email: 'guillaume@lfs.fr', role: 'OPS' },
  { id: '3', firstName: 'Mathéo', lastName: 'Degras', email: 'matheo@lfs.fr', role: 'OPS' },
  { id: '4', firstName: 'Lucas', lastName: 'Lamquet', email: 'lucas@lfs.fr', role: 'OPS' },
];

export const mockLeadDetails = (id: string) => {
  const lead = mockLeads.find(l => l.id === id) || mockLeads[0];
  return {
    ...lead,
    source: 'prospection',
    landUse: 'agricole',
    shading: 'faible',
    checklist: {
      SOURCING: [
        { id: 's1', label: 'Identification du terrain via satellite', completed: true, aiAssisted: true },
        { id: 's2', label: 'Vérification surface disponible', completed: true, aiAssisted: true },
        { id: 's3', label: 'Analyse topographique préliminaire', completed: true, aiAssisted: false },
      ],
      REGULATORY_ANALYSIS: [
        { id: 'r1', label: 'Extraction PLU automatique', completed: true, aiAssisted: true },
        { id: 'r2', label: 'Analyse compatibilité PLU', completed: true, aiAssisted: true },
        { id: 'r3', label: 'Vérification Natura 2000', completed: false, aiAssisted: true },
      ],
      TECHNICAL_STUDY: [
        { id: 't1', label: 'Données irradiation PVGIS', completed: false, aiAssisted: true },
        { id: 't2', label: 'Distribution mensuelle production', completed: false, aiAssisted: true },
      ],
    },
  };
};
